- name: Install Nginx
  notify: Restart Nginx service
  apt:
    state: present
    name: nginx

- name: Copy Nginx config file
  notify: Restart Nginx service
  copy:
    src: "{{ role_path }}/files/etc/nginx/nginx.conf"
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Copy multiple site files
  notify: Restart Nginx service
  copy:
    src: "{{ role_path }}/files/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-available/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    #- code-complete.co.uk
    - colleendavidson.co.uk
    - default

- name: Copy middletonscamping.com site template
  notify: Restart Nginx service
  template: 
    src: "{{ role_path }}/templates/etc/nginx/sites-available/middletonscamping.com"
    dest: /etc/nginx/sites-available/middletonscamping.com
    owner: root
    group: root
    mode: 0644

- name: Create multiple site links
  notify: Restart Nginx service
  file:
    state: link
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    owner: root
    group: root
  with_items:
    #- code-complete.co.uk
    - colleendavidson.co.uk
    - middletonscamping.com
    - default

- name: Copy Nginx service file
  notify: Restart Nginx service
  template:
    src: "{{ role_path }}/files/lib/systemd/system/nginx.service"
    dest: /lib/systemd/system/nginx.service
    owner: root
    group: root
    mode: 0644
